Add summary to main page and at the end of chapter
ct-itmo/networking pull request #2
Opened 2023-04-26 12:14 UTC by spcfox

2023-04-26 17:46 UTC, nsychev requested changes
Было бы ещё, наверное, здорово добавить на главную суммарное число баллов по всем заданиям. А так неплохо :)

cc @irdkwmnsb

2023-04-26 17:46 UTC, nsychev commented on networking/core/chapter.py
> +        scores = self.calculate_score(attempts)
Тут что-то странное происходит: `calculate_scores` всегда вызывается дважды — не очень понятно, зачем

2023-04-26 17:46 UTC, nsychev commented on networking/templates/util/summary.html
> +    {% endif %}
```suggestion
    {% if chapter_result.solved_tasks == chapter_result.total_tasks %}
    Все чекпоинты пройдены.
    {% else %}
    Вы прошли {{ chapter_result.solved_tasks }} из {{ chapter_result.total_tasks }} чекпоинтов. 
    {% endif %}
```

2023-04-26 17:46 UTC, nsychev commented on networking/templates/util/results.html
> +            {{ 0 }}
Вообще, не гарантируется эквивалентность `is_solved` и `score > 0`.

Подразумевается, что могут быть задания, за которые можно получить частичный балл какими-то «частичными» действиями.

`is_solved` означает что-то навроде «человек сделал всё, что мог» и «форму для сдачи надо скрыть» (при этом мог получить неполный балл — например, из-за просроченного дедлайна).

Я бы написал что-то вроде {{ task_result.score or 0 }}

2023-04-27 07:20 UTC, nsychev approved these changes

2023-04-27 07:20 UTC, merged

2023-04-27 07:38 UTC, nsychev commented
К сожалению, всё развалилось, см. c718aa6dcc05150862f00f6d30db582a30f90d04.

(надо бы тесты, конечно)

2023-04-27 08:55 UTC, spcfox commented
> К сожалению, всё развалилось, см. [c718aa6](https://github.com/ct-itmo/networking/commit/c718aa6dcc05150862f00f6d30db582a30f90d04).
> 
> (надо бы тесты, конечно)

ой, да, линтер я, конечно, я зря не запустил

2023-05-13 18:11 UTC, nsychev commented
Добавил +5 баллов за PR. Они отобразятся в первом чекпоинте первого задания.

2023-05-13 19:37 UTC, spcfox commented
> Добавил +5 баллов за PR. Они отобразятся в первом чекпоинте первого задания.

Правда ли, что ограничение в 90 баллов за дз для меня всё равно действует?

2023-05-13 21:42 UTC, nsychev commented
> Правда ли, что ограничение в 90 баллов за дз для меня всё равно действует?

Да